name: Halsallroadtrip
favicon: null
layout_spectrum: 0.73669
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fbee'
    - '#2c347f'
    - '#a71d37'
    - '#e2cb23'
    - '#9c9e96'
  brandStrength: 0.4520766260102391
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
