name: Halsallroadtrip
favicon: null
layout_spectrum: 0.49324
typography_spectrum: 0.06757
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Halsall Roadtrip
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fbee'
    - '#2c347f'
    - '#a71d37'
    - '#e2cb23'
    - '#9c9e96'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
